name: 'PR to Discord'
author: 'Team-Retrip'
description: 'sends PR notifications to Discord.'
branding:
  icon: 'award'
  color: 'blue'

inputs:
  discord_webhook_url:
    description: 'webhook URL of a Discord channel.'
    required: true
  pull_request:
    description: 'Pull request json.'
    required: false
    default: ${{ toJson(github.event.pull_request) }}

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        BODY: ${{ toJson(fromJson(inputs.pull_request).body) }}
        USERNAME: ${{ toJson(fromJson(inputs.pull_request).user.login) }}
        AVATAR_URL: ${{ toJson(fromJson(inputs.pull_request).user.avatar_url) }}
        TITLE: ${{ toJson(fromJson(inputs.pull_request).title) }}
        URL: ${{ toJson(fromJson(inputs.pull_request).html_url) }}
        ASSIGNEES: ${{ toJson(fromJson(inputs.pull_request).assignees) }}
        LABELS: ${{ toJson(fromJson(inputs.pull_request).labels) }}
      run: |
        PROBLEM=$(
          echo $BODY |
          grep -Pio 'http[\w\:\/\.\-\?\=\&]+' |
          head -1 ||
          echo "$URL"
        );
        
        TITLE=$(
          echo $TITLE |
          tr -d '"'
        );
        
        MENTIONS=$(
          echo $ASSIGNEES | 
          jq -r '.[] | "@"+.login' | 
          paste -sd " "
        );
        if [ -z "$MENTIONS" ]; then
          MENTIONS="담당자가 지정되지 않았습니다."
        fi

        LABELS_LIST=$(
          echo $LABELS |
          jq -r '.[] | .name' |
          paste -sd ", "
        );
        if [ -z "$LABELS_LIST" ]; then
          LABELS_LIST="없음"
        fi

        # 한국 시간(KST)으로 포맷 변경
        DATE_FORMATTED_KST=$(TZ='Asia/Seoul' date +'%Y-%m-%d %H:%M:%S')
        
        # 한국 시간을 UTC로 변환
        DATE_FORMATTED_UTC=$(date --utc +%Y-%m-%dT%H:%M:%SZ)

        echo "PROBLEM=$PROBLEM" >> $GITHUB_ENV;
        echo "USERNAME=$USERNAME" >> $GITHUB_ENV;
        echo "AVATAR_URL=$AVATAR_URL" >> $GITHUB_ENV;
        echo "TITLE=$TITLE" >> $GITHUB_ENV;
        echo "URL=$URL" >> $GITHUB_ENV;
        echo "MENTIONS=$MENTIONS" >> $GITHUB_ENV;
        echo "LABELS=$LABELS_LIST" >> $GITHUB_ENV;
        echo "TIMESTAMP_KST=$DATE_FORMATTED_KST" >> $GITHUB_ENV;
        echo "TIMESTAMP_UTC=$DATE_FORMATTED_UTC" >> $GITHUB_ENV;

    - shell: bash
      env:
        DATA: |
          {
            "username": ${{ env.USERNAME }},
            "avatar_url": ${{ env.AVATAR_URL }},
            "embeds": [
              {
                "title": "📌 Pull Request: ${{ env.TITLE }}",
                "description": "새로운 PR이 생성되었습니다! 아래의 정보를 확인하세요.",
                "url": ${{ env.URL }},
                "color": 3066993,
                "fields": [
                  {
                    "name": "🔗 Pull Request URL",
                    "value": ${{ env.PROBLEM }},
                    "inline": false
                  },
                  {
                    "name": "👤 작성자",
                    "value": ${{ env.USERNAME }},
                    "inline": true
                  },
                  {
                    "name": "📅 생성 날짜",
                    "value": "${{ env.TIMESTAMP_KST }}",
                    "inline": true
                  },
                  {
                    "name": "🛠️ 담당자",
                    "value": "${{ env.MENTIONS }}",
                    "inline": false
                  },
                  {
                    "name": "🏷️ 라벨",
                    "value": "${{ env.LABELS }}",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "PR Notification Bot • Team Retrip"
                },
                "timestamp": "${{ env.TIMESTAMP_UTC }}"
              }
            ]
          }
      run: >
        curl -X
        POST -H 'Content-type:application/json'
        -d "$DATA"
        ${{ inputs.discord_webhook_url }}
